### ISSUE TITLE
Why use this and not kubed?

### ISSUE THREAD

**Issue by naphta** [kuberty/kubebuilder-kuberdon#1]
Just spotted this project through slack (or at least the forked one from you @toonsevrin), and it just made me think why should I use this over something like [kubed](https://appscode.com/products/kubed/)?

**Comment by toonsevrin** [comment]
Hi @naphta, I am the sole developer in the upcoming Kuberty project :smile: [Kuberty](https://github.com/kuberty/kuberty) is going to be an opinionated kubernetes integration testing framework.

Anyways, as it's quite an advanced project, I wanted to re-familiarize myself with controller development first. One of the frictions we have at my company is having to install registry secrets for each namespace we deploy to, so I thought writing a solution to this would help me get familiar with the ecosystem again. 

To answer your question: I didn't know about kubed. Looks like it solves exactly the same usecase :smile: I'm probably still going to use Kuberdon once a stable version is released:
```bash
toon@toon-desktop:~/kubed$ rm -rf vendor && git ls-files | xargs cat | wc -l
8524
toon@toon-desktop:~/kubebuilder-kuberdon$ git ls-files | xargs cat | wc -l
2510
```

**Regarding the forking:**
toonsevrin/kubebuilder-kuberdon will be squashed to a single v1.0 commit and merged into this repository. Then kuberty/kuberdon (not using kubebuilder) will be removed and kuberty/kubebuilder-kuberdon will be transfered to kuberty/kuberdon.

**Comment by naphta** [comment]
I figured this was a question a few people might have once there's a product here so why not ask it. Makes sense to me!

**Comment by toonsevrin** [comment]
@naphta I'm glad you asked! I didn't know about kubed :)
